[package]
name = "binary-2"
version = "0.1.0"
authors = ["Denys Zariaiev <denys.zariaiev@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.lib-1]
path = "../lib-1"

[[package.metadata.wharf.binary]]
name = "binary-2"
path = "/usr/local/bin/binary-2"
cwd = "/"
