[workspace]
members = [
    "binary-1",
    "binary-2",
    "lib-1",
]

[workspace.metadata.wharf.config]
builder-image = "rust:latest"
release-image = "alpine:latest"
default-user = "root"
default-workdir = "/root"
