[workspace]
members = [
    "cargo-container-tools",
    "cargo-buildkit-frontend",
    "buildkit-proto",
    "buildkit-llb",
    "buildkit-frontend",
]

exclude = [
    "examples/workspace",
    "examples/single-bin",
    "examples/single-bin-with-frontend",
]
