[package]
name = "cargo-container-tools"
version = "0.2.0"
authors = ["Denys Zariaiev <denys.zariaiev@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
cargo = "0.37"
clap = "2.33"
failure = "0.1"
lazy_static = "1.0"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
