[package]
name = "cargo-container-tools"
version = "0.1.0"
authors = ["Denys Zariaiev <denys.zariaiev@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
clap = "2.32"
cargo = "0.31"
failure = "0.1"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
