[package]
name = "lib-1"
version = "0.1.0"
authors = ["Denys Zariaiev <denys.zariaiev@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "=1.1"

[dependencies.log]
git = "https://github.com/rust-lang-nursery/log.git"
tag = "0.4.0"
