[package]
name = "cargo-wharf"
version = "0.1.0"
authors = ["Denys Zariaiev <denys.zariaiev@gmail.com>"]
edition = "2018"

[dependencies]
cargo = "0.38"
clap = "2.33"
env_logger = "0.6"
failure = "0.1"
log = "0.4"
semver = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.5"
