name: Continuous integration
on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  clippy:
    name: Clippy lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true

      - name: Install clippy
        run: rustup component add clippy

      - name: Check with clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  fmt:
    name: Formatting lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          override: true

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Check the formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Print docker info
        run: docker info

      - name: Login to Docker Hub Registry
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Installing buildx
        run: .ci/install-buildx.sh

      - name: Install bats
        run: sudo npm install -g bats

      - name: Run integration tests
        run: bats -t tests/integration
        env:
          DOCKER_BUILDKIT: 1
          EXPORT_DOCKER_CACHE: 1

      - name: Dump dmesg output
        if: failure()
        run: dmesg

      - name: Dump buildkit logs
        if: failure()
        run: docker logs buildx_buildkit_ci-builder0

      - name: Dump docker logs
        if: failure()
        run: sudo journalctl -eu docker

  publish-cargo-wharf-frontend:
    name: Publish denzp/cargo-wharf-frontend:master
    runs-on: ubuntu-latest
    needs: [clippy, test, fmt, integration]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Print docker info
        run: docker info

      - name: Login to Docker Hub Registry
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Installing buildx
        run: .ci/install-buildx.sh

      - name: Build and push the image
        run: >-
          docker buildx build
          --push -f cargo-wharf-frontend/Cargo.toml .
          --tag denzp/cargo-wharf-frontend:master
          --build-arg manifest-path=cargo-wharf-frontend/Cargo.toml
          --build-arg features=container-tools-master

  publish-cargo-container-tools:
    name: Publish denzp/cargo-container-tools:master
    runs-on: ubuntu-latest
    needs: [clippy, test, fmt, integration]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Print docker info
        run: docker info

      - name: Login to Docker Hub Registry
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Installing buildx
        run: .ci/install-buildx.sh

      - name: Build and push the image
        run: >-
          docker buildx build
          --push -f cargo-container-tools/Cargo.toml .
          --tag denzp/cargo-container-tools:master
          --cache-from type=registry,ref=denzp/cargo-container-tools:cache
