name: Docker integration tests
on: [push]

jobs:
  test:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker version
      - run: DOCKER_BUILDKIT=1 bats tests/integration
